// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://osdfvbjagfyvdhtkndus.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9zZGZ2YmphZ2Z5dmRodGtuZHVzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0NzY1MjYsImV4cCI6MjA2ODA1MjUyNn0.DAWRcYchkmMESzRZPFXrf_ac4LjuptSC0oF6nb0mVYE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});